// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace StoreEmpowerment_Automation.NewUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class NewUIMap
    {
        public void homeScreenCheck()
        {
            if(!this.UIMyStockWindow.UIRecentItemsText.Exists)
            {
                Assert.Fail("Home Screen did not appear");
            }
        }

        public void RecentItemsTabClick()
        {
            Gesture.Tap(this.UIMyStockWindow.UIRecentItemsText);
            if(!this.UIMyStockWindow.UINoRecentItemsFoundText.Exists)
            {
                Assert.Fail("No Recent Items not displayed");
            }
        }

        public void SearchResultsTabClick()
        {
            Gesture.Tap(this.UIMyStockWindow.UISearchResultsText);
            if(!this.UIMyStockWindow.UINoItemsFoundText.Exists)
            {
                Assert.Fail("No items found not displayed");
            }
        }

        public void SearchClick()
        {
            Gesture.Tap(this.UIMyStockWindow.UISearchResultsText);
            Gesture.Tap(this.UIMyStockWindow.UISearchText);
            if(!this.UIMyStockWindow.UISearchTextEdit.Exists)
            {
                Assert.Fail("Product Search Page not displayed");
            }
        }
        
        #region Properties
        public UIMyStockWindow UIMyStockWindow
        {
            get
            {
                if ((this.mUIMyStockWindow == null))
                {
                    this.mUIMyStockWindow = new UIMyStockWindow();
                }
                return this.mUIMyStockWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMyStockWindow mUIMyStockWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIMyStockWindow : XamlWindow
    {
        
        public UIMyStockWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Availability";
            #endregion
        }
        
        #region Properties
        public XamlEdit UIPassWordEdit
        {
            get
            {
                if ((this.mUIPassWordEdit == null))
                {
                    this.mUIPassWordEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUIPassWordEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "passWord";
                    #endregion
                }
                return this.mUIPassWordEdit;
            }
        }
        
        public XamlEdit UIUserNameEdit
        {
            get
            {
                if ((this.mUIUserNameEdit == null))
                {
                    this.mUIUserNameEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUIUserNameEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "userName";
                    #endregion
                }
                return this.mUIUserNameEdit;
            }
        }
        
        public XamlComboBox UIDomainComboBox
        {
            get
            {
                if ((this.mUIDomainComboBox == null))
                {
                    this.mUIDomainComboBox = new XamlComboBox(this);
                    #region Search Criteria
                    this.mUIDomainComboBox.SearchProperties[XamlComboBox.PropertyNames.AutomationId] = "domain";
                    #endregion
                }
                return this.mUIDomainComboBox;
            }
        }
        
        public XamlButton UISigninButton
        {
            get
            {
                if ((this.mUISigninButton == null))
                {
                    this.mUISigninButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUISigninButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "signIn";
                    #endregion
                }
                return this.mUISigninButton;
            }
        }
        
        public XamlControl UIItemImage
        {
            get
            {
                if ((this.mUIItemImage == null))
                {
                    this.mUIItemImage = new XamlControl(this);
                    #region Search Criteria
                    this.mUIItemImage.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    #endregion
                }
                return this.mUIItemImage;
            }
        }
        
        public XamlText UISearchText
        {
            get
            {
                if ((this.mUISearchText == null))
                {
                    this.mUISearchText = new XamlText(this);
                    #region Search Criteria
                    this.mUISearchText.SearchProperties[XamlText.PropertyNames.AutomationId] = "Search";
                    #endregion
                }
                return this.mUISearchText;
            }
        }
        
        public XamlText UIScanText
        {
            get
            {
                if ((this.mUIScanText == null))
                {
                    this.mUIScanText = new XamlText(this);
                    #region Search Criteria
                    this.mUIScanText.SearchProperties[XamlText.PropertyNames.AutomationId] = "Scan";
                    #endregion
                }
                return this.mUIScanText;
            }
        }
        
        public XamlText UIRecentItemsText
        {
            get
            {
                if ((this.mUIRecentItemsText == null))
                {
                    this.mUIRecentItemsText = new XamlText(this);
                    #region Search Criteria
                    this.mUIRecentItemsText.SearchProperties[XamlText.PropertyNames.AutomationId] = "RecentItems";
                    #endregion
                }
                return this.mUIRecentItemsText;
            }
        }
        
        public XamlText UISearchResultsText
        {
            get
            {
                if ((this.mUISearchResultsText == null))
                {
                    this.mUISearchResultsText = new XamlText(this);
                    #region Search Criteria
                    this.mUISearchResultsText.SearchProperties[XamlText.PropertyNames.AutomationId] = "searchResults";
                    #endregion
                }
                return this.mUISearchResultsText;
            }
        }
        
        public XamlText UINoRecentItemsFoundText
        {
            get
            {
                if ((this.mUINoRecentItemsFoundText == null))
                {
                    this.mUINoRecentItemsFoundText = new XamlText(this);
                    #region Search Criteria
                    this.mUINoRecentItemsFoundText.SearchProperties[XamlText.PropertyNames.AutomationId] = "norecent";
                    #endregion
                }
                return this.mUINoRecentItemsFoundText;
            }
        }
        
        public XamlText UINoItemsFoundText
        {
            get
            {
                if ((this.mUINoItemsFoundText == null))
                {
                    this.mUINoItemsFoundText = new XamlText(this);
                    #region Search Criteria
                    this.mUINoItemsFoundText.SearchProperties[XamlText.PropertyNames.AutomationId] = "nosearch";
                    #endregion
                }
                return this.mUINoItemsFoundText;
            }
        }
        
        public XamlEdit UISearchTextEdit
        {
            get
            {
                if ((this.mUISearchTextEdit == null))
                {
                    this.mUISearchTextEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUISearchTextEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "searchText";
                    #endregion
                }
                return this.mUISearchTextEdit;
            }
        }
        
        public XamlText UICancelText
        {
            get
            {
                if ((this.mUICancelText == null))
                {
                    this.mUICancelText = new XamlText(this);
                    #region Search Criteria
                    this.mUICancelText.SearchProperties[XamlText.PropertyNames.AutomationId] = "cancel";
                    #endregion
                }
                return this.mUICancelText;
            }
        }
        
        public XamlControl UIItemImage1
        {
            get
            {
                if ((this.mUIItemImage1 == null))
                {
                    this.mUIItemImage1 = new XamlControl(this);
                    #region Search Criteria
                    this.mUIItemImage1.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    this.mUIItemImage1.SearchProperties["Instance"] = "3";
                    #endregion
                }
                return this.mUIItemImage1;
            }
        }
        
        public XamlControl UISearchIconImage
        {
            get
            {
                if ((this.mUISearchIconImage == null))
                {
                    this.mUISearchIconImage = new XamlControl(this);
                    #region Search Criteria
                    this.mUISearchIconImage.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    this.mUISearchIconImage.SearchProperties["AutomationId"] = "searchIcon";
                    #endregion
                }
                return this.mUISearchIconImage;
            }
        }
        
        public XamlControl UIScanIconImage
        {
            get
            {
                if ((this.mUIScanIconImage == null))
                {
                    this.mUIScanIconImage = new XamlControl(this);
                    #region Search Criteria
                    this.mUIScanIconImage.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    this.mUIScanIconImage.SearchProperties["AutomationId"] = "scanIcon";
                    #endregion
                }
                return this.mUIScanIconImage;
            }
        }
        
        public XamlText UIQuarterToDateText
        {
            get
            {
                if ((this.mUIQuarterToDateText == null))
                {
                    this.mUIQuarterToDateText = new XamlText(this);
                    #region Search Criteria
                    this.mUIQuarterToDateText.SearchProperties[XamlText.PropertyNames.AutomationId] = "qtrToDate";
                    #endregion
                }
                return this.mUIQuarterToDateText;
            }
        }
        
        public XamlText UILastQuarterText
        {
            get
            {
                if ((this.mUILastQuarterText == null))
                {
                    this.mUILastQuarterText = new XamlText(this);
                    #region Search Criteria
                    this.mUILastQuarterText.SearchProperties[XamlText.PropertyNames.AutomationId] = "lastQtr";
                    #endregion
                }
                return this.mUILastQuarterText;
            }
        }
        
        public XamlText UISettingsText
        {
            get
            {
                if ((this.mUISettingsText == null))
                {
                    this.mUISettingsText = new XamlText(this);
                    #region Search Criteria
                    this.mUISettingsText.SearchProperties[XamlText.PropertyNames.AutomationId] = "SettingsText";
                    #endregion
                }
                return this.mUISettingsText;
            }
        }
        
        public XamlText UIVersion101Text
        {
            get
            {
                if ((this.mUIVersion101Text == null))
                {
                    this.mUIVersion101Text = new XamlText(this);
                    #region Search Criteria
                    this.mUIVersion101Text.SearchProperties[XamlText.PropertyNames.AutomationId] = "Version";
                    #endregion
                }
                return this.mUIVersion101Text;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUIPassWordEdit;
        
        private XamlEdit mUIUserNameEdit;
        
        private XamlComboBox mUIDomainComboBox;
        
        private XamlButton mUISigninButton;
        
        private XamlControl mUIItemImage;
        
        private XamlText mUISearchText;
        
        private XamlText mUIScanText;
        
        private XamlText mUIRecentItemsText;
        
        private XamlText mUISearchResultsText;
        
        private XamlText mUINoRecentItemsFoundText;
        
        private XamlText mUINoItemsFoundText;
        
        private XamlEdit mUISearchTextEdit;
        
        private XamlText mUICancelText;
        
        private XamlControl mUIItemImage1;
        
        private XamlControl mUISearchIconImage;
        
        private XamlControl mUIScanIconImage;
        
        private XamlText mUIQuarterToDateText;
        
        private XamlText mUILastQuarterText;
        
        private XamlText mUISettingsText;
        
        private XamlText mUIVersion101Text;
        #endregion
    }
}
