// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace StoreEmpowerment_Automation.SearchResultsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using System.Threading.Tasks;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class SearchResults
    {
        async Task putDelay()
        {
            await Task.Delay(2000);
        }

        public async void searchTest()
        {
            Gesture.Tap(this.UIMyStockWindow.UISearchText);
            this.UIMyStockWindow.UISearchTextEdit.Text = "Milk";
            Gesture.Tap(this.UIItemWindow.UIKeyboardPane.UIEnterButton);
            await putDelay();
            if(!this.UIMyStockWindow.UIStoreListList.UIStoreEmpowermentprodListItem.Exists)
            {
                Assert.Fail("Product List did not appear");
            }

        }
        
        public void CancelTest()
        {
            Gesture.Tap(this.UIMyStockWindow.UISearchText);
            Gesture.Tap(this.UIMyStockWindow.UICancelText);
            if(!this.UIMyStockWindow.UISearchText.Exists)
            {
                Assert.Fail("Cancel did not function properly");
            }
        }
        #region Properties
        public UIMyStockWindow UIMyStockWindow
        {
            get
            {
                if ((this.mUIMyStockWindow == null))
                {
                    this.mUIMyStockWindow = new UIMyStockWindow();
                }
                return this.mUIMyStockWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMyStockWindow mUIMyStockWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIMyStockWindow : XamlWindow
    {
        
        public UIMyStockWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "My Stock";
            #endregion
        }
        
        #region Properties
        public XamlText UISearchText
        {
            get
            {
                if ((this.mUISearchText == null))
                {
                    this.mUISearchText = new XamlText(this);
                    #region Search Criteria
                    this.mUISearchText.SearchProperties[XamlText.PropertyNames.AutomationId] = "Search";
                    #endregion
                }
                return this.mUISearchText;
            }
        }
        
        public XamlEdit UISearchTextEdit
        {
            get
            {
                if ((this.mUISearchTextEdit == null))
                {
                    this.mUISearchTextEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUISearchTextEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "searchText";
                    #endregion
                }
                return this.mUISearchTextEdit;
            }
        }
        
        public XamlText UICancelText
        {
            get
            {
                if ((this.mUICancelText == null))
                {
                    this.mUICancelText = new XamlText(this);
                    #region Search Criteria
                    this.mUICancelText.SearchProperties[XamlText.PropertyNames.AutomationId] = "cancel";
                    #endregion
                }
                return this.mUICancelText;
            }
        }
        
        public UIStoreListList UIStoreListList
        {
            get
            {
                if ((this.mUIStoreListList == null))
                {
                    this.mUIStoreListList = new UIStoreListList(this);
                }
                return this.mUIStoreListList;
            }
        }
        
        public UIRecentListList UIRecentListList
        {
            get
            {
                if ((this.mUIRecentListList == null))
                {
                    this.mUIRecentListList = new UIRecentListList(this);
                }
                return this.mUIRecentListList;
            }
        }
        #endregion
        
        #region Fields
        private XamlText mUISearchText;
        
        private XamlEdit mUISearchTextEdit;
        
        private XamlText mUICancelText;
        
        private UIStoreListList mUIStoreListList;
        
        private UIRecentListList mUIRecentListList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIStoreListList : XamlList
    {
        
        public UIStoreListList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "storeList";
            #endregion
        }
        
        #region Properties
        public XamlListItem UIStoreEmpowermentprodListItem
        {
            get
            {
                if ((this.mUIStoreEmpowermentprodListItem == null))
                {
                    this.mUIStoreEmpowermentprodListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mUIStoreEmpowermentprodListItem.SearchProperties[XamlListItem.PropertyNames.Name] = "storeEmpowerment.productDetails";
                    #endregion
                }
                return this.mUIStoreEmpowermentprodListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mUIStoreEmpowermentprodListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIRecentListList : XamlList
    {
        
        public UIRecentListList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "recentList";
            #endregion
        }
        
        #region Properties
        public XamlListItem UITBritishSemiSkimmedMListItem
        {
            get
            {
                if ((this.mUITBritishSemiSkimmedMListItem == null))
                {
                    this.mUITBritishSemiSkimmedMListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mUITBritishSemiSkimmedMListItem.SearchProperties[XamlListItem.PropertyNames.Name] = "T. British Semi Skimmed Mlk2.272Ltr/4Pints\n5000436589457";
                    #endregion
                }
                return this.mUITBritishSemiSkimmedMListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mUITBritishSemiSkimmedMListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow : UITestControl
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties["FrameworkId"] = "UIX";
            #endregion
        }
        
        #region Properties
        public UIKeyboardPane UIKeyboardPane
        {
            get
            {
                if ((this.mUIKeyboardPane == null))
                {
                    this.mUIKeyboardPane = new UIKeyboardPane(this);
                }
                return this.mUIKeyboardPane;
            }
        }
        #endregion
        
        #region Fields
        private UIKeyboardPane mUIKeyboardPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIKeyboardPane : UITestControl
    {
        
        public UIKeyboardPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties["FrameworkId"] = "UIX";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Pane";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IPTip_Main_Window";
            this.SearchProperties["AutomationId"] = "Sip";
            #endregion
        }
        
        #region Properties
        public UITestControl UIEnterButton
        {
            get
            {
                if ((this.mUIEnterButton == null))
                {
                    this.mUIEnterButton = new UITestControl(this);
                    #region Search Criteria
                    this.mUIEnterButton.TechnologyName = "UIA";
                    this.mUIEnterButton.SearchProperties["FrameworkId"] = "UIX";
                    this.mUIEnterButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "Button";
                    this.mUIEnterButton.SearchProperties["AutomationId"] = "SIP_VK_0x0d";
                    #endregion
                }
                return this.mUIEnterButton;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mUIEnterButton;
        #endregion
    }
}
